### ISSUE TITLE
待整理

### ISSUE THREAD

**Issue by DeanPaul** [DeanPaul/blog#3]
当然两点需要简单说明的地方：

首先，你需要了解的是当 state 改变时，React 是如何更新我们的组件的。简单的说，当一个组件的状态改变时，它以及它所有后代的组件的 render 方法都会被调用一次，然后生成一个虚拟的 DOM 树再将它与内存中的虚拟的 DOM 树进行比较，然后采用最小代价的操作来更新浏览器中真实 DOM。因此，当我们通过 setState 方法更新状态的时候，React 看起来像是更新了整个 DOM 树。shouldComponentUpdate 提供了一种我们可以侵入到这个过程的能力，当该方法返回 false 的时候，该组件的 render 方法不会被调用，不会产生新的虚拟 DOM，该组件自然也没有后续虚拟 DOM 的 diff 和真实 DOM 更新。

其次，PureRenderMixin 只是浅比较 state 和 props ，只意味着你的 render 在相同的 state 和 props 的情况下必须要返回一致的输出，当你使用了复杂的数据类型来作为 state 和 prop 的时候，你可能需要引入 Immutable.js 这样的不可变数据类型的库。

通常情况下，它能够大幅提高你的应用的性能，尤其是你在构建一个复杂的应用的时候。当你使用类似于 Redux 这样的库用于集中管理你应用的 state 时，数据流总是从顶部单向流向各个层级的组件，因此意味着每一次 store 的变化，都会导致整个组件树中所有组件的 render 方法被调用一次，这也意味着引入 PureComponent 能够避免那些不必要的 render 方法被调用。

状态设计和无状态组件
关于状态的设计有些时候并不是一目了然，尤其是对新手来说。但是总结起来只有一条核心的原则，那就是尽量保证你的组件无状态 。这会让你的组件更容易理解和维护，也会让你整个应用的数据流更加清晰。

具体可以拆分为两条具体的原则，状态最小子集 和 状态集中管理 。状态最小集要求我们找到影响视图变化的状态的最小集合，而状态集中管理则要求我们使用类似 redux 这样的状态容器来集中管理我们的状态。实践中具体的技巧大概有以下 3 条：

消除组件内重复的状态
其核心是：

任何可以被计算或推导的数据不应该作为状态。

如果将可以被计算和推导出来的数据作为状态，那么就意味着你要维护和保持这些状态之间的同步，这通常是 bug 产生的地方，而且排查起来也很不容易。

消除组件间重复的状态
其核心是：

_ 任何除自身以及后代以外的组件会关注的数据不应该作为自身的状态_。

也就是通常提到的「向上顶」的原则。

这一条没有上一条那么直观，但却是很容易犯错的地方。任何除自身以及后代以外的组件通常意外着父组件或者其兄弟组件。

我举一个简单的例子，现在你要设计一个筛选器组件，它会涉及到很多筛选项，然后当用户提交的时候，页面下方的列表会更新。我们会很自然的将当前用户筛选的值作为该组件内部的一个状态，由该组件内部跟新和维护，然后在用户点击的确定的时候，通过暴露一个 onSubmit 事件，将参数传递给父组件，如组件更新列表。类似如下：

class Filter extends React.Component {
    constructor(props) {
        super(props)

        this.state = {
            foo: props.defaultFoo,
            bar: props.defaultBar
        }
    }

    handleBarChange(newBar) {
        this.setState({
            bar: newBar
        })
    }

    handleFooChange(newFoo) {
        this.setState({
            foo: newFoo
        })
    }

    handleSubmit() {
        const { bar, foo } = this.state
        this.props.onSubmit({ bar, foo })
    }

    render () {
        //...
    }
}
这样做会带来很多问题，比如如组件如果还接受其他的筛选条件来更新列表，比如翻页，那么意味这父组件必须要在 onSubmit 事件中不得不保存该筛选条件，可能将它存到 state 里面，那就意味同一份数据在父组件中也保存了一份相同的引用，同时意味着你要时刻小心的保持两者的同步。再比如，我现在用一个弹窗或者下拉框的形式来展现这些筛选条件，也就是说，但用户筛选完成之后，如果并没有点击提交，而是直接关闭了弹窗。那么当用户再次点开弹窗的时候，你需要重置会已生效的筛选条件，这个时候你又不得不将 props 同步给 state。

接下来我们进行改进，筛选项的值父组件是会关注的，所以「向上顶」放到父组件里面去。大概如下：

class Filter extends React.Component {
    constructor(props) {
        super(props)
    }

    handleBarChange(newBar) {
        const {value, onChange} = this.props

        onChange(Object.assign({}, value, {bar: newBar}))
    }

    handleFooChange(newFoo) {
        const {value, onChange} = this.props

        onChange(Object.assign({}, value, {foo: newFoo}))
    }

    handleSubmit() {
        this.props.onSubmit()
    }

    render () {
        //...
    }
}
然后 Filter 组件变得很清晰明了，仅仅负责将父组件传入的筛选项信息 value 正确的渲染，同时暴露 onChange 和 onSubmit 父组件，将筛选状态的维护工作拆分给了父组件。而我上面提到的 2 个问题也就迎刃而解了。

通过以上 2 条技巧，我们很容易消除那些重复的状态，保证我们应用处于最小状态集合中。同时能够衍生出一条简单的准则帮助你发现问题，那就是当你发现你在维护两个状态的同步时，通常意味着你的组件设计有问题，如果两个状态在同一个组件内，参考技巧 1，否则参考技巧 2。

现在保证了状态最小集合，但要达到无状态组件，还需要我们将这些状态移除我们的组件，也就是接下来第 3 条技巧。

使用状态容器管理状态
这一条技巧很简单，就是使用例如 redux 这样的状态容器来集中管理我们应用中的状态，尤其是在构建复杂的应用的时候。关于 redux 的使用，社区里面有很多相关的教程，这里不再赘述。

最后，值得一提的是，我们是否应该将所有的状态都移除组件，达到真正的无状态组件。答案是否定的，因为这样不仅将会导致实践中流程极其繁琐，甚至某些时候也是不必要的。

但某些时候，又是什么时候？

简单的想一下我们浏览器自带的 select 元素，选择器是否展开必然应该作为一个状态。但是我们没有需要将其作为一个属性传给元素来控制元素是否展开，而且 select 元素确实也没有这个属性。因此，这个原则就是：

当某个状态之后该组件自身会关注，其余组件（父类和子类等等）都不关注的时候，那么你可以将它作为状态保留到组件内部。

关注 ComponentDidUpdate
最后，我想说明一下 ComponentDidUpdate 这个方法，这个方法经常被大家忽略，但其实应该有着更大的用武之地。

对于 React 而言，理想情况下应该是，我们设计好状态以及状态和视图的关联关系以后，在随后时间推移和用户交互的过程中我们只需要更改我们的状态就可以了。但实际情况是，我们很多时候在更改状态（例如，筛选项等）之后还需要去服务器上请求相应的数据。我们最常见的做法是在 setState 的回调函数里，如果使用了 类似于 redux 的状态管理容器时，我们可能派发一个异步 Action。

// setState 回调
function handlePageChange(newPage) {
    this.setState(
        { page: newPage },

        () => this.fetchData()
    );
}

// dipatch 异步的 action
function fetchDataWithPageChange(page) {
    return async (dispatch, getState) => {
        // 同步的 action
        dispatch(pageChange(page));

        const query = getState().query;

        // 异步操作
        let res = await get(url, Object.assign({ page }, query));

        // 同步 action
        dispatch(dataChange(res));
    }
}
这样做最大的问题是，我们将我们改变状态的行为和数据请求耦合在了一起，而当其他同样需要请求相同数据的状态改变之后，我们也必须记着调用相同的数据请求的方法，需要小心翼翼，不能遗忘。

如果我们把状态变化与数据请求的关系写在 componentDidUpdate 里面，那么我们就能够专注的更新我们的状态，因为状态更新会自动触发数据请求。看到了吗？这个我们处理状态和视图的关系如此相似，一旦指定了映射关系，那么只需要简单更新状态，就能自动触发另一方相应的动作。

改进如果下：

class Com extends PureComponent {
    // ...
    handlePageChange(newPage) {
        this.setState({
            page: newPage
        });
    }

    componentDidUpdate(preProps, preState) {
        const { page } = preState;

        if (page !== this.state.page) {
            this.fetchData();
        }
    }
    // ...
}

// 或者
class Com extends PureComponent {
    // ...
    handlePageChange(newPage) {
        this.props.dispatch(changePage(newPage));
    }

    componentDidUpdate(preProps) {
        const { page } = preProps;

        if (page !== this.props.page) {
            this.props.dispatch(fetchData());
        }
    }
    // ...
}

function changePage(page) {
    return {
        type: 'CHANGE_PAGE',
        index: page
    };
}
总结
关于 React 的总结和最佳实践暂时想到的就这些，从使用了 React 之后，在我需要构建一个在线的应用之前（不管是否使用 React ），我都会先首先梳理页面视图随着时间推移和用户的交互时是如何变化的，具体到 React 就是整个 app 的数据流。它们就像是一栋建筑的设计稿和结构图，等到你深入其中的细枝末节的时候仍然给能够对整体了然于胸，不会被一叶蔽目。我很享受这个过程，希望你们也能喜欢。

**Comment by DeanPaul** [comment]
连等
function 内部var 变量提升

**Comment by DeanPaul** [comment]
new Function

**Comment by DeanPaul** [comment]
callee

**Comment by DeanPaul** [comment]
## Array 类型
### 创建数组
```
var s = new Date();for(let i =0;i<500000000;i++) a =new Array();console.log(new Date()-s)
var s = new Date();for(let i =0;i<500000000;i++) a =[];console.log(new Date()-s)
```

### 检测数组
```
value instanceof Array //？？
Array.isArray(value)
```

### 转换方法
```
var colors = ["red", "blue", "green"]; // 创建一个包含 3 个字符串的数组
alert(colors.toString()); // red,blue,green
alert(colors.valueOf()); // red,blue,green
alert(colors); // red,blue,green 

var person1 = {
 toLocaleString : function () {
 return "Nikolaos";
 },

 toString : function() {
 return "Nicholas";
 }
};
var person2 = {
 toLocaleString : function () {
 return "Grigorios";
 },

 toString : function() {
 return "Greg";
 }
};
var people = [person1, person2];
alert(people); //Nicholas,Greg
alert(people.toString()); //Nicholas,Greg
alert(people.toLocaleString());
```
### join
Q1
let keyWords = ["GCD","He","I"];
let content = "Fu GCD is He and I am your ki";
替换 key words to "逗号"

### 栈方法
栈是一种 LIFO（Last-In-First-Out，后进先出）的数据结构，
```
var colors = new Array(); // 创建一个数组
var count = colors.push("red", "green"); // 推入两项
alert(count); //2
count = colors.push("black"); // 推入另一项
alert(count); //3
var item = colors.pop(); // 取得最后一项
alert(item); //"black"
alert(colors.length); //2 
```
### 队列方法
队列数据结构的访问规则是 FIFO（First-In-First-Out，先进先出）
```
var colors = new Array(); //创建一个数组
var count = colors.push("red", "green"); //推入两项
alert(count); //2
count = colors.push("black"); //推入另一项
alert(count); //3
var item = colors.shift(); //取得第一项
alert(item); //"red"
alert(colors.length); //2 
```
Q2 
shift后数组index情况如何
### unshift()方法
顾名思义，unshift()与 shift()的用途相反：
它能在数组前端添加任意个项并返回新数组的长度
```
var colors = new Array(); //创建一个数组
var count = colors.unshift("red", "green"); //推入两项
count = colors.unshift("black"); //推入另一项
alert(count); //3
var item = colors.pop(); //取得最后一项
alert(item); //"green" 
```
### 排序方法
reverse()和 sort()
var values = [1, 2, 3, 4, 5];
values.reverse();
alert(values); //5,4,3,2,1 
-----------------------------------
var values = [0, 1, 5, 10, 15];
values.sort();
alert(values); //0,1,10,15,5 
-----------------------------------
function compare(value1, value2) {
 if (value1 < value2) {
 return -1;
 } else if (value1 > value2) {
 return 1;
 } else {
 return 0;
 }
} 
var values = [0, 1, 5, 10, 15];
values.sort(compare);
alert(values); //0,1,5,10,15 
### 操作方法
concat
在没有给 concat()方法传递参数的情况下，它只是复制当前数组并返回副本。
如果传递给 concat()方法的是一或多个数组，则该方法会将这些数组中的每一项都添加到结果数组中。
如果传递的值不是数组，这些值就会被简单地添加到结果数组的末尾
```
var colors = ["red", "green", "blue"];
var colors2 = colors.concat("yellow", ["black", "brown"]);
alert(colors); //red,green,blue
alert(colors2); //red,green,blue,yellow,black,brown
```
slice
slice()方法不会影响原始数组
```
var colors = ["red", "green", "blue", "yellow", "purple"];
var colors2 = colors.slice(1);
var colors3 = colors.slice(1,4); 
```
splice
 删除：可以删除任意数量的项，只需指定 2 个参数：要删除的第一项的位置和要删除的项数。
例如，splice(0,2)会删除数组中的前两项。
 插入：可以向指定位置插入任意数量的项，只需提供 3 个参数：起始位置、0（要删除的项数）
和要插入的项。如果要插入多个项，可以再传入第四、第五，以至任意多个项。例如，
splice(2,0,"red","green")会从当前数组的位置 2 开始插入字符串"red"和"green"。
 替换：可以向指定位置插入任意数量的项，且同时删除任意数量的项，只需指定 3 个参数：起
始位置、要删除的项数和要插入的任意数量的项。插入的项数不必与删除的项数相等。例如，
splice (2,1,"red","green")会删除当前数组位置 2 的项，然后再从位置 2 开始插入字符串"red"和"green"。
```
var colors = ["red", "green", "blue"];
var removed = colors.splice(0,1); // 删除第一项
alert(colors); // green,blue
alert(removed); // red，返回的数组中只包含一项
removed = colors.splice(1, 0, "yellow", "orange"); // 从位置 1 开始插入两项
alert(colors); // green,yellow,orange,blue
alert(removed); // 返回的是一个空数组
removed = colors.splice(1, 1, "red", "purple"); // 插入两项，删除一项
alert(colors); // green,red,purple,orange,blue
alert(removed); // yellow，返回的数组中只包含一项
```
### 位置方法
indexOf()和 lastIndexOf()
 === 
### 迭代方法
 every()：对数组中的每一项运行给定函数，如果该函数对每一项都返回 true，则返回 true。
 filter()：对数组中的每一项运行给定函数，返回该函数会返回 true 的项组成的数组。
 forEach()：对数组中的每一项运行给定函数。这个方法没有返回值。
 map()：对数组中的每一项运行给定函数，返回每次函数调用的结果组成的数组。
 some()：对数组中的每一项运行给定函数，如果该函数对任一项返回 true，则返回 true。
都不会修改数组中的包含的值
### 归并方法
reduce()和 reduceRight()
```
var values = [1,2,3,4,5];
var sum = values.reduce(function(prev, cur, index, array){
 return prev + cur;
});
alert(sum); //15 

```

**Comment by DeanPaul** [comment]
### Date类型
### RegExp 类型

**Comment by DeanPaul** [comment]
### Function 类型
var f1 = function
var f2 = f1
连等
function 内部var 变量提升
new Function
callee

**Comment by DeanPaul** [comment]
### 基本包装类型
String
substr()和 substring()

### 单体内置对象

Global对象
“兜底儿对象”
如 isNaN()、isFinite()、parseInt()以及 parseFloat()，实际上全都是 Global
对象的方法。除此之外，Global 对象还包含其他一些方法
URI 编码方法
encodeURI()和 encodeURIComponent()
```
var uri = "http://www.wrox.com/illegal value.htm#start";
//"http://www.wrox.com/illegal%20value.htm#start"
alert(encodeURI(uri));
//"http%3A%2F%2Fwww.wrox.com%2Fillegal%20value.htm%23start"
alert(encodeURIComponent(uri)); 
```
 eval()
 window 对象

### Math对象

**Comment by xiaodanlee** [comment]
let keyWords = ["GCD","He","I"];
let content = "Fu GCD is He and I am your ki";
let keys = keyWords.join("")
let cons = content.split(" ");
cons.reduce((prev,cur)=>{
  return keys.indexOf(cur)>-1 ? prev+",":prev+" "+cur
}
